name: build

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: tweedge/requests-html-layer:latest

      - name: Test
        run: |
          docker run --rm tweedge/requests-html-layer:latest

      - name: Push
        uses: docker/build-push-action@v6
        with:
          load: true
          push: true
          tags: tweedge/requests-html-layer:latest

      - name: Generate SBOM for image
        uses: anchore/sbom-action@v0
        with:
          image: tweedge/requests-html-layer:latest